#!/usr/bin/env bash
# Safe self-restart for Cardloop, with a pre-restart wait-for-idle and a post-restart
# health/log canary + one-shot rollback (spec-072).
#
# Why (original hazard, still true): calling `sudo systemctl restart/stop cardloop`
# directly from a shell inside the bot kills that shell — it lives in the service's
# cgroup, and systemctl tears down the entire cgroup MID-COMMAND. So `stop && start`
# never reaches start and the bot stays down (this is how it killed itself on
# 2026-05-30, see CLAUDE.md).
#
# Solution: systemd-run launches the restart in a SEPARATE transient unit outside
# the service's cgroup — it survives the bot's death and reliably completes the restart.
#
# spec-072 additions:
#   1. Pre-restart wait-for-idle (this shell, before scheduling anything): poll
#      GET /api/health?deep=1 (unauthenticated — see webapp.py's auth_middleware
#      exempt list; it only leaks a count) until running==0, up to 10 minutes, then
#      proceed anyway with a loud warning. Best-effort: any failure to reach the API
#      (service down, fresh install, no curl) skips straight to the restart — this
#      must never be what blocks a restart.
#   2. Post-restart canary (generated as a standalone script and run INSIDE the
#      detached transient unit, NOT this caller shell — this shell must return
#      immediately per the cgroup rule above): poll /api/health up to 60s, scan the
#      journal since the restart for new Traceback/FATAL lines (excluding known
#      teardown noise), smoke-GET / and /api/health. On failure: roll back to the
#      previous git tag ONCE, rebuild web/, restart again, and leave a loud red
#      incident marker (journal + data/inbox/, surfaced in the cockpit). Never loops
#      — one rollback attempt max, then leave it down loud.
#
# CANARY_DRY_RUN=1 skips the actual systemd-run call (used to shell-check/exercise
# the wait-for-idle + canary-script-generation logic without touching systemd).
set -euo pipefail

# Systemd unit name — OSS default "cardloop"; overridable via CARDLOOP_SERVICE (env or .env) so an
# existing deployment installed under a different unit name keeps restarting correctly.
DIR="$(cd "$(dirname "$0")" && pwd)"
SERVICE="${CARDLOOP_SERVICE:-}"
if [ -z "$SERVICE" ] && [ -f "$DIR/.env" ]; then
  # `|| true`: a no-match grep exits 1, which under `set -e`+pipefail would abort
  # this script before scheduling the restart. Default installs DON'T set
  # CARDLOOP_SERVICE in .env, so without this the self-update never restarts.
  SERVICE="$(grep -E '^[[:space:]]*CARDLOOP_SERVICE=' "$DIR/.env" 2>/dev/null | tail -n1 | cut -d= -f2- | awk '{print $1}' | tr -d '"')" || true
fi
SERVICE="${SERVICE:-cardloop}"

# WEB_PORT — same env-or-.env resolution pattern as SERVICE above (default 8787).
WEB_PORT="${WEB_PORT:-}"
if [ -z "$WEB_PORT" ] && [ -f "$DIR/.env" ]; then
  WEB_PORT="$(grep -E '^[[:space:]]*WEB_PORT=' "$DIR/.env" 2>/dev/null | tail -n1 | cut -d= -f2- | awk '{print $1}' | tr -d '"')" || true
fi
WEB_PORT="${WEB_PORT:-8787}"
BASE_URL="http://127.0.0.1:${WEB_PORT}"

# ─────────────────────────── Pre-restart: wait-for-idle ───────────────────────────
WAIT_FOR_IDLE_MAX_SEC="${WAIT_FOR_IDLE_MAX_SEC:-600}"
if command -v curl >/dev/null 2>&1; then
  echo "Waiting for idle (no in-flight turns) before restarting ${SERVICE}, up to ${WAIT_FOR_IDLE_MAX_SEC}s..."
  waited=0
  while [ "$waited" -lt "$WAIT_FOR_IDLE_MAX_SEC" ]; do
    resp="$(curl -fsS --max-time 3 "${BASE_URL}/api/health?deep=1" 2>/dev/null || true)"
    if [ -z "$resp" ]; then
      # API unreachable (service down, or a fresh install before its first start) —
      # nothing to wait for; proceed immediately rather than spinning for 10 minutes.
      break
    fi
    # Python's json.dumps inserts a space after ':' by default ({"running": 1}) —
    # tolerate an optional space so this doesn't silently misparse as "idle".
    running="$(printf '%s' "$resp" | grep -oE '"running"[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+$' || true)"
    if [ -z "$running" ] || [ "$running" = "0" ]; then
      break
    fi
    sleep 5
    waited=$((waited + 5))
  done
  if [ "$waited" -ge "$WAIT_FOR_IDLE_MAX_SEC" ]; then
    echo "⚠️  WARNING: still busy after ${WAIT_FOR_IDLE_MAX_SEC}s wait — restarting anyway (in-flight turns will be aborted)."
  fi
else
  echo "curl not found — skipping wait-for-idle (restarting immediately)."
fi

# ─────────────────────────── Post-restart canary script ───────────────────────────
# Generated as a standalone script and handed to systemd-run so it executes AFTER
# the restart, from the detached transient unit — never from this caller shell.
# Values baked in below (DIR/SERVICE/BASE_URL) are fixed at generation time; the
# escaped `\$...` bits are evaluated later, when the canary script itself runs.
CANARY_SCRIPT="$(mktemp "${TMPDIR:-/tmp}/cardloop-canary.XXXXXX.sh")"

cat > "$CANARY_SCRIPT" << CANARY_EOF
#!/usr/bin/env bash
# Auto-generated by restart-self.sh (spec-072) — runs once, inside the detached
# transient unit, after the restart. Self-deletes at the end (see bottom).
set -uo pipefail
DIR="$DIR"
SERVICE="$SERVICE"
BASE_URL="$BASE_URL"

log() { echo "[canary] \$*"; command -v logger >/dev/null 2>&1 && logger -t cardloop-canary "\$*" || true; }

RESTART_TS="\$(date '+%Y-%m-%d %H:%M:%S')"

# 1. Poll /api/health up to 60s (best-effort — no curl means we can't verify, so
#    assume healthy rather than false-triggering a rollback for a missing tool).
healthy=0
if command -v curl >/dev/null 2>&1; then
  for _ in \$(seq 1 30); do
    if curl -fsS --max-time 2 "\${BASE_URL}/api/health" >/dev/null 2>&1; then
      healthy=1
      break
    fi
    sleep 2
  done
else
  log "curl not found — skipping health poll (assuming healthy)"
  healthy=1
fi

# 2. Scan the journal since the restart for new Traceback/FATAL lines, excluding
#    known benign teardown noise (bot.py's bounded-teardown-timeout warning prints
#    a line containing "WARNING" that is expected, not a real failure).
bad_logs=0
if command -v journalctl >/dev/null 2>&1; then
  since="\$(date -d '-2 minutes' '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo "\$RESTART_TS")"
  logs="\$(journalctl -u "\$SERVICE" --since "\$since" --no-pager 2>/dev/null || true)"
  suspicious="\$(printf '%s\n' "\$logs" | grep -E 'Traceback|FATAL' | grep -v 'WARNING: bounded teardown timed out' || true)"
  if [ -n "\$suspicious" ]; then
    bad_logs=1
    log "suspicious log line(s) since restart:"
    printf '%s\n' "\$suspicious" | while IFS= read -r line; do log "  \$line"; done
  fi
else
  log "journalctl not found — skipping log scan"
fi

# 3. Smoke-GET / and /api/health.
smoke_ok=1
if command -v curl >/dev/null 2>&1; then
  curl -fsS --max-time 5 "\${BASE_URL}/" >/dev/null 2>&1 || smoke_ok=0
  curl -fsS --max-time 5 "\${BASE_URL}/api/health" >/dev/null 2>&1 || smoke_ok=0
fi

if [ "\$healthy" = "1" ] && [ "\$bad_logs" = "0" ] && [ "\$smoke_ok" = "1" ]; then
  log "canary OK — \$SERVICE healthy after restart"
  rm -f "\$0"
  exit 0
fi

log "canary FAILED (healthy=\$healthy bad_logs=\$bad_logs smoke_ok=\$smoke_ok) — attempting one-shot rollback"

# ─────────────────────────── One-shot rollback (never loops) ───────────────────
cd "\$DIR" || { log "cannot cd to \$DIR — giving up, service left as-is"; rm -f "\$0"; exit 1; }

prev_tag="\$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || true)"
if [ -z "\$prev_tag" ]; then
  log "no previous tag found (git describe --tags --abbrev=0 HEAD^) — cannot roll back; leaving service as-is"
  incident="INCIDENT: restart canary failed for \$SERVICE at \$RESTART_TS, and no previous git tag was found to roll back to. Service may be unhealthy — check manually (journalctl -u \$SERVICE)."
elif git checkout "\$prev_tag" 2>&1 | while IFS= read -r l; do log "  git: \$l"; done; then
  log "rolled back to \$prev_tag"
  rebuild_ok=1
  if [ -d web ] && command -v npm >/dev/null 2>&1; then
    if ! (cd web && npm run build) >/tmp/cardloop-rollback-build.log 2>&1; then
      rebuild_ok=0
      log "web rebuild FAILED after rollback — restarting old code WITHOUT a fresh dist (see /tmp/cardloop-rollback-build.log)"
    fi
  else
    log "npm or web/ not found — skipping frontend rebuild"
  fi
  sudo systemctl restart "\$SERVICE" 2>&1 | while IFS= read -r l; do log "  systemctl: \$l"; done
  incident="INCIDENT: restart canary failed for \$SERVICE at \$RESTART_TS — rolled back to \$prev_tag (frontend rebuild_ok=\$rebuild_ok) and restarted. Investigate before deploying again."
else
  incident="INCIDENT: restart canary failed for \$SERVICE at \$RESTART_TS, AND rollback to \$prev_tag failed (git checkout error — dirty tree?). Service left as-is — needs manual attention."
fi

log "\$incident"
mkdir -p "\$DIR/data/inbox" 2>/dev/null || true
printf '🔴 %s\n' "\$incident" >> "\$DIR/data/inbox/canary-incident-\$(date +%s).txt" 2>/dev/null || true
rm -f "\$0"
exit 1
CANARY_EOF
chmod +x "$CANARY_SCRIPT"

if [ "${CANARY_DRY_RUN:-0}" = "1" ]; then
  echo "CANARY_DRY_RUN=1 — skipping systemd-run. Generated canary script (not executed, not auto-deleted): $CANARY_SCRIPT"
  exit 0
fi

# --on-active=6: the delay must be comfortably LONGER than the time the harness
# needs to commit the current turn/response. At 1s the restart SIGTERM-ed the agent
# turn process (which lives in the same cgroup) BEFORE the tool-call result was
# committed, causing the harness to show a spurious "Command failed with exit code 143".
# 6s gives the turn enough time to complete and be delivered; the restart fires later
# with no visible error. The canary runs right after, inside this same detached unit —
# `;` (not `&&`) so it still runs and logs even if the restart itself failed outright.
sudo systemd-run --collect --quiet \
  --unit="cardloop-self-restart-$(date +%s)" \
  --on-active=6 --timer-property=AccuracySec=200ms \
  /bin/bash -c "systemctl restart '$SERVICE'; bash '$CANARY_SCRIPT'"

echo "Restart of ${SERVICE} scheduled (~6s, detached via systemd-run, outside cgroup)."
echo "   Post-restart canary (health/log-scan, one-shot rollback on failure) runs inside that same detached unit."
echo "   Finish your turn IMMEDIATELY after this command (no further bash) — web cockpit (:8787) will come back up on its own."
