"""spec-052 Phases 5-6 — keep each spec's generated ## Tasks mirror in sync with
the board, and detect when all of a spec's linked cards are done (auto-close).

Design (see spec-052 §4 Phases 5-6, absorbs spec-049):
- A card links to a spec via the ops-marker attribute `spec=<id>` (board.py).
- Each spec file gets a generated, delimited `## Tasks` block listing its cards
  with live status. The block is the PERSISTENT spec→cards record: a card id
  survives in it even after the card is archived to DONE.md (which keeps the id
  but drops the spec attr), so "all cards done" stays detectable.
- "done" = the card id is present in DONE.md. A card that is neither linked-open
  nor in DONE.md (deleted / unlinked) is dropped from the mirror.
- Auto-close (Phase 6b) is expressed INSIDE the generated block (a "✅ Complete"
  header line) + a board_event from the caller. On the close transition we also
  stamp the spec's status (spec-059 Move 5) — but ONLY when the current status is
  a placeholder (draft / empty / wip…); a curated status is left untouched so a
  multi-phase spec's hand-written "[x] Phase A shipped" never gets clobbered.
  Handles both YAML `status:` frontmatter and an inline `**Status:**`/`**Статус:**`.
"""
import re
import time
from pathlib import Path

from board import _load_board, _done_path, _MARKER_RE, _parse_marker_meta

_MIRROR_BEGIN = "<!-- spec-tasks:begin (generated by Cardloop — do not edit) -->"
_MIRROR_END = "<!-- spec-tasks:end -->"
_STATUS_GLYPH = {
    "backlog": "○",
    "in_progress": "◐",
    "review": "✓",
    "failed": "✗",
    "done": "✓",
}
# Pull card ids out of a prior mirror block line: "- [glyph] [id] text"
_MIRROR_LINE_RE = re.compile(r"^- \[.\] \[([\w-]+)\]")

# spec-059 Move 5 — status auto-stamp on auto-close.
# Only a placeholder status (the operator hasn't curated it) is overwritten; any
# other value is treated as deliberate and left alone. Compared case-insensitively.
_AUTO_STATUS_OVERWRITE = {
    "", "draft", "todo", "to-do", "planned", "proposed", "idea",
    "wip", "in progress", "in-progress", "in_progress",
}
# Value-only captured in group(2) so the prefix is preserved on rewrite.
# [ \t]* (not \s*) so the value never reaches into the next line.
_YAML_STATUS_LINE_RE = re.compile(r"^(status:[ \t]*)(.*)$", re.MULTILINE)
_BOLD_STATUS_LINE_RE = re.compile(
    r"^(\*\*(?:Status|Статус):\*\*[ \t]*)(.*)$", re.MULTILINE | re.IGNORECASE)


def _default_specs_dir(cwd: str) -> Path:
    # Each project keeps its specs in its own repo (gitignored).
    return Path(cwd) / "docs" / "internal" / "specs"


def _resolve_spec_file(spec_id: str, specs_dir: Path) -> Path | None:
    """spec-<id>-*.md (prefer exact spec-<id>.md). Returns None if no file."""
    exact = specs_dir / f"spec-{spec_id}.md"
    if exact.exists():
        return exact
    matches = sorted(specs_dir.glob(f"spec-{spec_id}-*.md"))
    return matches[0] if matches else None


def _done_ids(cwd: str) -> set[str]:
    dp = _done_path(cwd)
    if not dp.exists():
        return set()
    try:
        text = dp.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return set()
    # _MARKER_RE anchors on the closing '-->' so it doesn't over-capture (group 1 = id).
    return {m.group(1) for m in _MARKER_RE.finditer(text)}


def _done_cards_for_spec(cwd: str, spec_id: str) -> dict:
    """{id: title} for cards in DONE.md whose marker carries spec=<spec_id>.
    Robust: lets a done card be tracked even if it was never mirrored while open
    (the spec= is preserved in the archive line by board._done_archive_line)."""
    dp = _done_path(cwd)
    if not dp.exists():
        return {}
    try:
        text = dp.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return {}
    out: dict = {}
    for line in text.splitlines():
        m = _MARKER_RE.search(line)
        if not m:
            continue
        meta = _parse_marker_meta(m.group(2))
        if meta.get("spec") != spec_id:
            continue
        tm = re.match(r"^\s*[-*]\s*\[.\]\s*(.*?)\s*<!--", line)
        out[m.group(1)] = (tm.group(1).strip() if tm and tm.group(1).strip() else m.group(1))
    return out


def _prior_mirror_ids(spec_text: str) -> list[str]:
    """Card ids previously recorded in the spec's ## Tasks block (order preserved)."""
    begin = spec_text.find(_MIRROR_BEGIN)
    end = spec_text.find(_MIRROR_END)
    if begin == -1 or end == -1 or end < begin:
        return []
    block = spec_text[begin:end]
    ids: list[str] = []
    for line in block.splitlines():
        m = _MIRROR_LINE_RE.match(line.strip())
        if m:
            ids.append(m.group(1))
    return ids


def _render_block(rows: list[tuple[str, str, str]], all_done: bool) -> str:
    """rows = [(glyph, id, text)]. Returns the full delimited block text."""
    total = len(rows)
    done = sum(1 for g, _, _ in rows if g == _STATUS_GLYPH["done"])
    if total == 0:
        header = "_(no linked cards yet)_"
    elif all_done:
        header = f"✅ Complete — {done}/{total} cards done"
    else:
        header = f"_{done}/{total} cards done_"
    lines = [_MIRROR_BEGIN, header]
    for glyph, cid, text in rows:
        lines.append(f"- [{glyph}] [{cid}] {text}")
    lines.append(_MIRROR_END)
    return "\n".join(lines)


def _shipped_status() -> str:
    """The status value stamped on auto-close — date-stamped for traceability."""
    return f"shipped ({time.strftime('%Y-%m-%d')})"


def _frontmatter_body_span(text: str) -> tuple[int, int] | None:
    """(start, end) char offsets of the YAML frontmatter body — between the opening
    '---' and the next '\\n---' — or None when the file has no leading frontmatter."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    return (3, end) if end != -1 else None


def _stamp_status(spec_text: str, status_value: str) -> tuple[str, bool]:
    """Set the spec's status to status_value when the CURRENT status is a placeholder
    (draft / empty / wip…); a curated status is left untouched. A spec with YAML
    frontmatter is stamped via its `status:` line (no-op if it has none); otherwise an
    inline `**Status:**`/`**Статус:**` line is used. Frontmatter wins, matching the
    read path in spec_epics._parse_spec_meta. Returns (new_text, changed)."""
    span = _frontmatter_body_span(spec_text)
    if span is not None:
        body = spec_text[span[0]:span[1]]
        m = _YAML_STATUS_LINE_RE.search(body)
        if not m:
            return spec_text, False  # frontmatter spec without a status: field — leave it
        if m.group(2).strip().lower() not in _AUTO_STATUS_OVERWRITE:
            return spec_text, False
        new_body = body[:m.start(2)] + status_value + body[m.end(2):]
        return spec_text[:span[0]] + new_body + spec_text[span[1]:], True
    # No frontmatter — try an inline bold status line.
    m = _BOLD_STATUS_LINE_RE.search(spec_text)
    if not m:
        return spec_text, False
    if m.group(2).strip().lower() not in _AUTO_STATUS_OVERWRITE:
        return spec_text, False
    return spec_text[:m.start(2)] + status_value + spec_text[m.end(2):], True


def sync_spec_mirror(cwd: str, spec_id: str, *, specs_dir: Path | None = None) -> dict | None:
    """Regenerate the ## Tasks mirror for one spec from the current board state.

    Returns a summary dict {spec_id, file, total, done, all_done, newly_closed}
    or None when the spec file does not exist (link kept on the card, skip+caller logs).
    """
    specs_dir = specs_dir or _default_specs_dir(cwd)
    if not specs_dir.exists():
        return None
    spec_file = _resolve_spec_file(spec_id, specs_dir)
    if spec_file is None:
        return None

    try:
        spec_text = spec_file.read_text(encoding="utf-8")
    except OSError:
        return None

    # Currently-linked open cards (any board column incl. failed).
    _, _, cols = _load_board(cwd)
    linked: dict[str, tuple[str, str]] = {}  # id -> (col_key, text)
    for col_key, cards in cols.items():
        for c in cards:
            if c.get("spec") == spec_id:
                linked[c["id"]] = (col_key, c["text"])

    done = _done_ids(cwd)                       # all done ids (for prior back-compat)
    done_for_spec = _done_cards_for_spec(cwd, spec_id)  # done cards whose marker keeps spec=
    prior = _prior_mirror_ids(spec_text)

    # Card set = linked-open ∪ done-cards-tagged-with-this-spec
    #            ∪ (prior ids now in DONE.md — back-compat for cards archived before
    #              the spec= attribute was preserved in DONE.md).
    # Prior ids that are neither linked nor done were deleted/unlinked → dropped.
    ordered_ids: list[str] = []
    seen: set[str] = set()
    for cid in prior + list(linked.keys()) + list(done_for_spec.keys()):
        if cid in seen:
            continue
        if cid in linked or cid in done_for_spec or cid in done:
            seen.add(cid)
            ordered_ids.append(cid)

    rows: list[tuple[str, str, str]] = []
    for cid in ordered_ids:
        if cid in linked:
            col_key, text = linked[cid]
            rows.append((_STATUS_GLYPH.get(col_key, "○"), cid, text))
        else:  # done (in DONE.md, no longer on the open board)
            text = done_for_spec.get(cid) or _done_text(cwd, cid)
            rows.append((_STATUS_GLYPH["done"], cid, text))

    total = len(rows)
    done_count = sum(1 for g, _, _ in rows if g == _STATUS_GLYPH["done"])
    # all_done: at least one card and none still open (every relevant id is done).
    all_done = total > 0 and not any(cid in linked for cid in ordered_ids)

    block = _render_block(rows, all_done)
    new_text, changed = _splice_block(spec_text, block)

    # newly_closed: the block now says complete AND it didn't before.
    was_complete = "✅ Complete" in spec_text[
        spec_text.find(_MIRROR_BEGIN):spec_text.find(_MIRROR_END)
    ] if (_MIRROR_BEGIN in spec_text and _MIRROR_END in spec_text) else False
    newly_closed = all_done and not was_complete

    # spec-059 Move 5: on the close transition, stamp a placeholder status → shipped.
    # Only the transition stamps (newly_closed is False on later runs), so it never churns.
    status_stamped = False
    if newly_closed:
        new_text, status_stamped = _stamp_status(new_text, _shipped_status())
        if status_stamped:
            changed = True

    if changed:
        try:
            spec_file.write_text(new_text, encoding="utf-8")
        except OSError:
            return None

    return {
        "spec_id": spec_id,
        "file": str(spec_file),
        "total": total,
        "done": done_count,
        "all_done": all_done,
        "newly_closed": newly_closed,
        "status_stamped": status_stamped,
    }


def _done_text(cwd: str, cid: str) -> str:
    """Best-effort card title from DONE.md for an archived id; falls back to the id."""
    dp = _done_path(cwd)
    if not dp.exists():
        return cid
    try:
        for line in dp.read_text(encoding="utf-8", errors="replace").splitlines():
            if f"ops:{cid}" in line:
                m = re.match(r"^\s*[-*]\s*\[.\]\s*(.*?)\s*<!--", line)
                if m and m.group(1).strip():
                    return m.group(1).strip()
    except OSError:
        pass
    return cid


def _splice_block(spec_text: str, block: str) -> tuple[str, bool]:
    """Replace the existing mirror block, or create a '## Tasks' section at EOF.
    Returns (new_text, changed)."""
    begin = spec_text.find(_MIRROR_BEGIN)
    end = spec_text.find(_MIRROR_END)
    if begin != -1 and end != -1 and end > begin:
        end_full = end + len(_MIRROR_END)
        new_text = spec_text[:begin] + block + spec_text[end_full:]
        return new_text, (new_text != spec_text)
    # No block yet — append a fresh '## Tasks' section.
    sep = "" if spec_text.endswith("\n") else "\n"
    section = f"{sep}\n## Tasks\n\n{block}\n"
    return spec_text + section, True
